version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 main.py'
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image:
      postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
