version: '3.8'

services:
  backend:
    container_name: fastapi
    build: ./src
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 /app/src/main.py'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - src/.env
    depends_on:
      - db
  db:
    container_name: pgdb
    image:
      postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/.env
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro


volumes:
  postgres_data:
