from sqlalchemy.orm import Session

from crud.words import create_word
from models import Word
from src.crud import create_hiragana, create_katakana
from src.models import Hiragana, Katakana


def load_hiragana(db: Session):
    create_hiragana(db, Hiragana(hiragana="あ", romaji="a"))
    create_hiragana(db, Hiragana(hiragana="い", romaji="i"))
    create_hiragana(db, Hiragana(hiragana="う", romaji="u"))
    create_hiragana(db, Hiragana(hiragana="え", romaji="e"))
    create_hiragana(db, Hiragana(hiragana="お", romaji="o"))
    create_hiragana(db, Hiragana(hiragana="か", romaji="ka"))
    create_hiragana(db, Hiragana(hiragana="き", romaji="ki"))
    create_hiragana(db, Hiragana(hiragana="く", romaji="ku"))
    create_hiragana(db, Hiragana(hiragana="け", romaji="ke"))
    create_hiragana(db, Hiragana(hiragana="こ", romaji="ko"))
    create_hiragana(db, Hiragana(hiragana="さ", romaji="sa"))
    create_hiragana(db, Hiragana(hiragana="し", romaji="shi"))
    create_hiragana(db, Hiragana(hiragana="す", romaji="su"))
    create_hiragana(db, Hiragana(hiragana="せ", romaji="se"))
    create_hiragana(db, Hiragana(hiragana="そ", romaji="so"))
    create_hiragana(db, Hiragana(hiragana="た", romaji="ta"))
    create_hiragana(db, Hiragana(hiragana="ち", romaji="chi"))
    create_hiragana(db, Hiragana(hiragana="つ", romaji="tsu"))
    create_hiragana(db, Hiragana(hiragana="て", romaji="te"))
    create_hiragana(db, Hiragana(hiragana="と", romaji="to"))
    create_hiragana(db, Hiragana(hiragana="な", romaji="na"))
    create_hiragana(db, Hiragana(hiragana="に", romaji="ni"))
    create_hiragana(db, Hiragana(hiragana="ぬ", romaji="nu"))
    create_hiragana(db, Hiragana(hiragana="ね", romaji="ne"))
    create_hiragana(db, Hiragana(hiragana="の", romaji="no"))
    create_hiragana(db, Hiragana(hiragana="は", romaji="ha"))
    create_hiragana(db, Hiragana(hiragana="ひ", romaji="hi"))
    create_hiragana(db, Hiragana(hiragana="ふ", romaji="fu"))
    create_hiragana(db, Hiragana(hiragana="へ", romaji="he"))
    create_hiragana(db, Hiragana(hiragana="ほ", romaji="ho"))
    create_hiragana(db, Hiragana(hiragana="ま", romaji="ma"))
    create_hiragana(db, Hiragana(hiragana="み", romaji="mi"))
    create_hiragana(db, Hiragana(hiragana="む", romaji="mu"))
    create_hiragana(db, Hiragana(hiragana="め", romaji="me"))
    create_hiragana(db, Hiragana(hiragana="も", romaji="mo"))
    create_hiragana(db, Hiragana(hiragana="や", romaji="ya"))
    create_hiragana(db, Hiragana(hiragana="ゆ", romaji="yu"))
    create_hiragana(db, Hiragana(hiragana="よ", romaji="yo"))
    create_hiragana(db, Hiragana(hiragana="ら", romaji="ra"))
    create_hiragana(db, Hiragana(hiragana="り", romaji="ri"))
    create_hiragana(db, Hiragana(hiragana="る", romaji="ru"))
    create_hiragana(db, Hiragana(hiragana="れ", romaji="re"))
    create_hiragana(db, Hiragana(hiragana="ろ", romaji="ro"))
    create_hiragana(db, Hiragana(hiragana="わ", romaji="wa"))
    create_hiragana(db, Hiragana(hiragana="を", romaji="wo"))
    create_hiragana(db, Hiragana(hiragana="ん", romaji="n"))
    create_hiragana(db, Hiragana(hiragana="が", romaji="ga"))
    create_hiragana(db, Hiragana(hiragana="ぎ", romaji="gi"))
    create_hiragana(db, Hiragana(hiragana="ぐ", romaji="gu"))
    create_hiragana(db, Hiragana(hiragana="げ", romaji="ge"))
    create_hiragana(db, Hiragana(hiragana="ご", romaji="go"))
    create_hiragana(db, Hiragana(hiragana="ざ", romaji="za"))
    create_hiragana(db, Hiragana(hiragana="じ", romaji="ji"))
    create_hiragana(db, Hiragana(hiragana="ず", romaji="zu"))
    create_hiragana(db, Hiragana(hiragana="ぜ", romaji="ze"))
    create_hiragana(db, Hiragana(hiragana="ぞ", romaji="zo"))
    create_hiragana(db, Hiragana(hiragana="だ", romaji="da"))
    create_hiragana(db, Hiragana(hiragana="ぢ", romaji="ji"))
    create_hiragana(db, Hiragana(hiragana="づ", romaji="zu"))
    create_hiragana(db, Hiragana(hiragana="で", romaji="de"))
    create_hiragana(db, Hiragana(hiragana="ど", romaji="do"))
    create_hiragana(db, Hiragana(hiragana="ば", romaji="ba"))
    create_hiragana(db, Hiragana(hiragana="び", romaji="bi"))
    create_hiragana(db, Hiragana(hiragana="ぶ", romaji="bu"))
    create_hiragana(db, Hiragana(hiragana="べ", romaji="be"))
    create_hiragana(db, Hiragana(hiragana="ぼ", romaji="bo"))
    create_hiragana(db, Hiragana(hiragana="ぱ", romaji="pa"))
    create_hiragana(db, Hiragana(hiragana="ぴ", romaji="pi"))
    create_hiragana(db, Hiragana(hiragana="ぷ", romaji="pu"))
    create_hiragana(db, Hiragana(hiragana="ぺ", romaji="pe"))
    create_hiragana(db, Hiragana(hiragana="ぽ", romaji="po"))
    create_hiragana(db, Hiragana(hiragana="きゃ", romaji="kya"))
    create_hiragana(db, Hiragana(hiragana="きゅ", romaji="kyu"))
    create_hiragana(db, Hiragana(hiragana="きょ", romaji="kyo"))
    create_hiragana(db, Hiragana(hiragana="しゃ", romaji="sha"))
    create_hiragana(db, Hiragana(hiragana="しゅ", romaji="shu"))
    create_hiragana(db, Hiragana(hiragana="しょ", romaji="sho"))
    create_hiragana(db, Hiragana(hiragana="ちゃ", romaji="cha"))
    create_hiragana(db, Hiragana(hiragana="ちゅ", romaji="chu"))
    create_hiragana(db, Hiragana(hiragana="ちょ", romaji="cho"))
    create_hiragana(db, Hiragana(hiragana="にゃ", romaji="nya"))
    create_hiragana(db, Hiragana(hiragana="にゅ", romaji="nyu"))
    create_hiragana(db, Hiragana(hiragana="にょ", romaji="nyo"))
    create_hiragana(db, Hiragana(hiragana="ひゃ", romaji="hya"))
    create_hiragana(db, Hiragana(hiragana="ひゅ", romaji="hyu"))
    create_hiragana(db, Hiragana(hiragana="ひょ", romaji="hyo"))
    create_hiragana(db, Hiragana(hiragana="みゃ", romaji="mya"))
    create_hiragana(db, Hiragana(hiragana="みゅ", romaji="myu"))
    create_hiragana(db, Hiragana(hiragana="みょ", romaji="myo"))
    create_hiragana(db, Hiragana(hiragana="りゃ", romaji="rya"))
    create_hiragana(db, Hiragana(hiragana="りゅ", romaji="ryu"))
    create_hiragana(db, Hiragana(hiragana="りょ", romaji="ryo"))
    create_hiragana(db, Hiragana(hiragana="ぎゃ", romaji="gya"))
    create_hiragana(db, Hiragana(hiragana="ぎゅ", romaji="gyu"))
    create_hiragana(db, Hiragana(hiragana="ぎょ", romaji="gyo"))
    create_hiragana(db, Hiragana(hiragana="じゃ", romaji="ja"))
    create_hiragana(db, Hiragana(hiragana="じゅ", romaji="ju"))
    create_hiragana(db, Hiragana(hiragana="じょ", romaji="jo"))
    create_hiragana(db, Hiragana(hiragana="びゃ", romaji="bya"))
    create_hiragana(db, Hiragana(hiragana="びゅ", romaji="byu"))
    create_hiragana(db, Hiragana(hiragana="びょ", romaji="byo"))
    create_hiragana(db, Hiragana(hiragana="ぴゃ", romaji="pya"))
    create_hiragana(db, Hiragana(hiragana="ぴゅ", romaji="pyu"))
    create_hiragana(db, Hiragana(hiragana="ぴょ", romaji="pyo"))


def load_katakana(db: Session):
    create_katakana(db, Katakana(katakana='ア', romaji='a'))
    create_katakana(db, Katakana(katakana='イ', romaji='i'))
    create_katakana(db, Katakana(katakana='ウ', romaji='u'))
    create_katakana(db, Katakana(katakana='エ', romaji='e'))
    create_katakana(db, Katakana(katakana='オ', romaji='o'))
    create_katakana(db, Katakana(katakana='カ', romaji='ka'))
    create_katakana(db, Katakana(katakana='キ', romaji='ki'))
    create_katakana(db, Katakana(katakana='ク', romaji='ku'))
    create_katakana(db, Katakana(katakana='ケ', romaji='ke'))
    create_katakana(db, Katakana(katakana='コ', romaji='ko'))
    create_katakana(db, Katakana(katakana='サ', romaji='sa'))
    create_katakana(db, Katakana(katakana='シ', romaji='shi'))
    create_katakana(db, Katakana(katakana='ス', romaji='su'))
    create_katakana(db, Katakana(katakana='セ', romaji='se'))
    create_katakana(db, Katakana(katakana='ソ', romaji='so'))
    create_katakana(db, Katakana(katakana='タ', romaji='ta'))
    create_katakana(db, Katakana(katakana='チ', romaji='chi'))
    create_katakana(db, Katakana(katakana='ツ', romaji='tsu'))
    create_katakana(db, Katakana(katakana='テ', romaji='te'))
    create_katakana(db, Katakana(katakana='ト', romaji='to'))
    create_katakana(db, Katakana(katakana='ナ', romaji='na'))
    create_katakana(db, Katakana(katakana='ニ', romaji='ni'))
    create_katakana(db, Katakana(katakana='ヌ', romaji='nu'))
    create_katakana(db, Katakana(katakana='ネ', romaji='ne'))
    create_katakana(db, Katakana(katakana='ノ', romaji='no'))
    create_katakana(db, Katakana(katakana='ハ', romaji='ha'))
    create_katakana(db, Katakana(katakana='ヒ', romaji='hi'))
    create_katakana(db, Katakana(katakana='フ', romaji='fu'))
    create_katakana(db, Katakana(katakana='ヘ', romaji='he'))
    create_katakana(db, Katakana(katakana='ホ', romaji='ho'))
    create_katakana(db, Katakana(katakana='マ', romaji='ma'))
    create_katakana(db, Katakana(katakana='ミ', romaji='mi'))
    create_katakana(db, Katakana(katakana='ム', romaji='mu'))
    create_katakana(db, Katakana(katakana='メ', romaji='me'))
    create_katakana(db, Katakana(katakana='モ', romaji='mo'))
    create_katakana(db, Katakana(katakana='ヤ', romaji='ya'))
    create_katakana(db, Katakana(katakana='ユ', romaji='yu'))
    create_katakana(db, Katakana(katakana='ヨ', romaji='yo'))
    create_katakana(db, Katakana(katakana='ラ', romaji='ra'))
    create_katakana(db, Katakana(katakana='リ', romaji='ri'))
    create_katakana(db, Katakana(katakana='ル', romaji='ru'))
    create_katakana(db, Katakana(katakana='レ', romaji='re'))
    create_katakana(db, Katakana(katakana='ロ', romaji='ro'))
    create_katakana(db, Katakana(katakana='ワ', romaji='wa'))
    create_katakana(db, Katakana(katakana='ヲ', romaji='wo'))
    create_katakana(db, Katakana(katakana='ン', romaji='n'))
    create_katakana(db, Katakana(katakana='ガ', romaji='ga'))
    create_katakana(db, Katakana(katakana='ギ', romaji='gi'))
    create_katakana(db, Katakana(katakana='グ', romaji='gu'))
    create_katakana(db, Katakana(katakana='ゲ', romaji='ge'))
    create_katakana(db, Katakana(katakana='ゴ', romaji='go'))
    create_katakana(db, Katakana(katakana='ザ', romaji='za'))
    create_katakana(db, Katakana(katakana='ジ', romaji='ji'))
    create_katakana(db, Katakana(katakana='ズ', romaji='zu'))
    create_katakana(db, Katakana(katakana='ゼ', romaji='ze'))
    create_katakana(db, Katakana(katakana='ゾ', romaji='zo'))
    create_katakana(db, Katakana(katakana='ダ', romaji='da'))
    create_katakana(db, Katakana(katakana='ヂ', romaji='ji'))
    create_katakana(db, Katakana(katakana='ヅ', romaji='zu'))
    create_katakana(db, Katakana(katakana='デ', romaji='de'))
    create_katakana(db, Katakana(katakana='ド', romaji='do'))
    create_katakana(db, Katakana(katakana='バ', romaji='ba'))
    create_katakana(db, Katakana(katakana='ビ', romaji='bi'))
    create_katakana(db, Katakana(katakana='ブ', romaji='bu'))
    create_katakana(db, Katakana(katakana='ベ', romaji='be'))
    create_katakana(db, Katakana(katakana='ボ', romaji='bo'))
    create_katakana(db, Katakana(katakana='パ', romaji='pa'))
    create_katakana(db, Katakana(katakana='ピ', romaji='pi'))
    create_katakana(db, Katakana(katakana='プ', romaji='pu'))
    create_katakana(db, Katakana(katakana='ペ', romaji='pe'))
    create_katakana(db, Katakana(katakana='ポ', romaji='po'))
    create_katakana(db, Katakana(katakana='キャ', romaji='kya'))
    create_katakana(db, Katakana(katakana='キュ', romaji='kyu'))
    create_katakana(db, Katakana(katakana='キョ', romaji='kyo'))
    create_katakana(db, Katakana(katakana='シャ', romaji='sha'))
    create_katakana(db, Katakana(katakana='シュ', romaji='shu'))
    create_katakana(db, Katakana(katakana='ショ', romaji='sho'))
    create_katakana(db, Katakana(katakana='チャ', romaji='cha'))
    create_katakana(db, Katakana(katakana='チュ', romaji='chu'))
    create_katakana(db, Katakana(katakana='チョ', romaji='cho'))
    create_katakana(db, Katakana(katakana='ニャ', romaji='nya'))
    create_katakana(db, Katakana(katakana='ニュ', romaji='nyu'))
    create_katakana(db, Katakana(katakana='ニョ', romaji='nyo'))
    create_katakana(db, Katakana(katakana='ヒャ', romaji='hya'))
    create_katakana(db, Katakana(katakana='ヒュ', romaji='hyu'))
    create_katakana(db, Katakana(katakana='ヒョ', romaji='hyo'))
    create_katakana(db, Katakana(katakana='ミャ', romaji='mya'))
    create_katakana(db, Katakana(katakana='ミュ', romaji='myu'))
    create_katakana(db, Katakana(katakana='ミョ', romaji='myo'))
    create_katakana(db, Katakana(katakana='リャ', romaji='rya'))
    create_katakana(db, Katakana(katakana='リュ', romaji='ryu'))
    create_katakana(db, Katakana(katakana='リョ', romaji='ryo'))
    create_katakana(db, Katakana(katakana='ギャ', romaji='gya'))
    create_katakana(db, Katakana(katakana='ギュ', romaji='gyu'))
    create_katakana(db, Katakana(katakana='ギョ', romaji='gyo'))
    create_katakana(db, Katakana(katakana='ジャ', romaji='ja'))
    create_katakana(db, Katakana(katakana='ジュ', romaji='ju'))
    create_katakana(db, Katakana(katakana='ジョ', romaji='jo'))
    create_katakana(db, Katakana(katakana='ビャ', romaji='bya'))
    create_katakana(db, Katakana(katakana='ビュ', romaji='byu'))
    create_katakana(db, Katakana(katakana='ビョ', romaji='byo'))
    create_katakana(db, Katakana(katakana='ピャ', romaji='pya'))
    create_katakana(db, Katakana(katakana='ピュ', romaji='pyu'))
    create_katakana(db, Katakana(katakana='ピョ', romaji='pyo'))


def load_words(db: Session):
    create_word(db, Word(word='ばん', meaning='number...', reading=''))
    create_word(db, Word(word='医者', meaning='doctor', reading='いしゃ'))
    create_word(db, Word(word='今', meaning='now', reading='いま'))
    create_word(db, Word(word='妹', meaning='younger sister', reading='いもうと'))
    create_word(db, Word(word='お父さん', meaning='father', reading='おとうさん'))
    create_word(db, Word(word='弟', meaning='younger brother', reading='おとうと'))
    create_word(db, Word(word='お兄さん', meaning='older brother', reading='おにいさん'))
    create_word(db, Word(word='お姉さん', meaning='older sister', reading='おねえさん'))
    create_word(db, Word(word='かいしゃいん', meaning='office worker', reading=''))
    create_word(db, Word(word='学生', meaning='student', reading='がくせい'))
    create_word(db, Word(word='高校', meaning='high school', reading='こうこう'))
    create_word(db, Word(word='午後', meaning='pm', reading='ごご'))
    create_word(db, Word(word='午前', meaning='am', reading='ごぜん'))
    create_word(db, Word(word='しゅふ', meaning='house wife', reading=''))
    create_word(db, Word(word='先生', meaning='teacher, skilled one', reading='せんせい'))
    create_word(db, Word(word='大学', meaning='university, college', reading='だいがく'))
    create_word(db, Word(word='電話', meaning='phone, phone call', reading='でんわ'))
    create_word(db, Word(word='友達', meaning='friend, companion', reading='ともだち'))
    create_word(db, Word(word='番号', meaning='number', reading='ばんごう'))
    create_word(db, Word(word='べんごし', meaning='lawyer', reading=''))
    create_word(db, Word(word='こんばんわ', meaning='good evening', reading=''))
    create_word(db, Word(word='さようなら', meaning='bye', reading=''))
    create_word(db, Word(word='こんにちは', meaning='good afternoon', reading=''))
    create_word(db, Word(word='おはようございます', meaning='good morning', reading=''))
    create_word(db, Word(word='おやすみ', meaning='good night', reading=''))
    create_word(db, Word(word='すみません', meaning='excuse me', reading=''))
    create_word(db, Word(word='いってきます', meaning='im going out', reading=''))
    create_word(db, Word(word='いってらっしゃい', meaning='come back', reading=''))
    create_word(db, Word(word='ただいま', meaning='im home', reading=''))
    create_word(db, Word(word='おかえり', meaning='welcome home', reading=''))
    create_word(db, Word(word='いただきます', meaning='have a good meal', reading=''))
    create_word(db, Word(word='ごちそうさま', meaning='thank you for the meal', reading=''))
    create_word(db, Word(word='はじめまして', meaning='how are you doing', reading=''))
    create_word(db, Word(word='よろしくおねがいします', meaning='nice to meet you', reading=''))
    create_word(db, Word(word='じゃあまた', meaning='bye,', reading=''))
    create_word(db, Word(word='しつれいします', meaning='sorry', reading=''))
    create_word(db, Word(word='韓国', meaning='korea', reading='かんこく'))
    create_word(db, Word(word='中国', meaning='china', reading='ちゅうごく'))
    create_word(db, Word(word='どちらから', meaning='where are you from', reading=''))
    create_word(db, Word(word='教師', meaning='teacher', reading='きょうし'))
    create_word(db, Word(word='夫', meaning='husband', reading='おっと'))
    create_word(db, Word(word='兄', meaning='my older brother', reading='あに'))
    create_word(db, Word(word='姉', meaning='my older sister', reading='あね'))
    create_word(db, Word(word='家族', meaning='family, household', reading='かぞく'))
    create_word(db, Word(word='妻', meaning='wife', reading='つま'))
    create_word(db, Word(word='野菜', meaning='vegetable', reading='やさい'))
    create_word(db, Word(word='果物', meaning='fruit', reading='くだもの'))
    create_word(db, Word(word='卵', meaning='egg', reading='たまご'))
    create_word(db, Word(word='パン', meaning='bread', reading=''))
    create_word(db, Word(word='魚', meaning='fish', reading='さかな'))
    create_word(db, Word(word='肉', meaning='meat, flesh', reading='にく'))
    create_word(db, Word(word='味噌汁', meaning='miso soup', reading='みそしる'))
    create_word(db, Word(word='食べ物', meaning='food', reading='たべもの'))
    create_word(db, Word(word='飲み物', meaning='drinks', reading='のみもの'))
    create_word(db, Word(word='コーヒー', meaning='coffee', reading=''))
    create_word(db, Word(word='紅茶', meaning='black tea', reading='こうちゃ'))
    create_word(db, Word(word='牛乳', meaning='milk', reading='ぎゅうにゅう'))
    create_word(db, Word(word='水', meaning='water', reading='みず'))
    create_word(db, Word(word='ジュース', meaning='juice', reading=''))
    create_word(db, Word(word='ビール', meaning='beer', reading=''))
    create_word(db, Word(word='これ', meaning='this one', reading=''))
    create_word(db, Word(word='それ', meaning='that one', reading=''))
    create_word(db, Word(word='あれ', meaning='that one over there', reading=''))
    create_word(db, Word(word='どれ', meaning='which one', reading=''))
    create_word(db, Word(word='この', meaning='this', reading=''))
    create_word(db, Word(word='その', meaning='that', reading=''))
    create_word(db, Word(word='あの', meaning='that over there', reading=''))
    create_word(db, Word(word='どの', meaning='which', reading=''))
    create_word(db, Word(word='ここ', meaning='here', reading=''))
    create_word(db, Word(word='そこ', meaning='there', reading=''))
    create_word(db, Word(word='あそこ', meaning='over there', reading=''))
    create_word(db, Word(word='どこ', meaning='where', reading=''))
    create_word(db, Word(word='誰', meaning='who', reading='だれ'))
    create_word(db, Word(word='傘', meaning='umbrella', reading='かさ'))
    create_word(db, Word(word='おいしい', meaning='delicious', reading=''))
    create_word(db, Word(word='鞄', meaning='bag', reading='かばん'))
    create_word(db, Word(word='靴', meaning='shoes', reading='くつ'))
    create_word(db, Word(word='財布', meaning='wallet, purse', reading='さいふ'))
    create_word(db, Word(word='自転車', meaning='bike', reading='じてんしゃ'))
    create_word(db, Word(word='新聞', meaning='newspaper', reading='しんぶん'))
    create_word(db, Word(word='スマホ', meaning='smartphone', reading=''))
    create_word(db, Word(word='時計', meaning='watch, clock', reading='とけい'))
    create_word(db, Word(word='ノート', meaning='notebook, laptop', reading=''))
    create_word(db, Word(word='百', meaning='100', reading='ひゃく'))
    create_word(db, Word(word='ろっぴゃく', meaning='600', reading=''))
    create_word(db, Word(word='銀行', meaning='bank', reading='ぎんこう'))
    create_word(db, Word(word='コンビニ', meaning='convinence store', reading=''))
    create_word(db, Word(word='トイレ', meaning='toilet', reading=''))
    create_word(db, Word(word='図書館', meaning='library', reading='としょかん'))
    create_word(db, Word(word='郵便局', meaning='post office', reading='ゆうびんきょく'))
    create_word(db, Word(word='どうぞ', meaning='here it is', reading=''))
    create_word(db, Word(word='どうも', meaning='thank you', reading=''))
    create_word(db, Word(word='さんびゃく', meaning='300', reading=''))
    create_word(db, Word(word='はっぴゃく', meaning='800', reading=''))
    create_word(db, Word(word='さんぜん', meaning='3000', reading=''))
    create_word(db, Word(word='はっせん', meaning='8000', reading=''))
    create_word(db, Word(word='映画', meaning='movie', reading='えいが'))
    create_word(db, Word(word='音楽', meaning='music', reading='おんがく'))
    create_word(db, Word(word='雑誌', meaning='magazine', reading='ざっし'))
    create_word(db, Word(word='お茶', meaning='green tea', reading='おちゃ'))
    create_word(db, Word(word='朝ご飯', meaning='breakfast', reading='あさごはん'))
    create_word(db, Word(word='昼ご飯', meaning='lunch', reading='ひるごはん'))
    create_word(db, Word(word='晩ご飯', meaning='dinner', reading='ばんごはん'))
    create_word(db, Word(word='家', meaning='home', reading='いえ'))
    create_word(db, Word(word='うち', meaning='house', reading=''))
    create_word(db, Word(word='学校', meaning='school', reading='がっこう'))
    create_word(db, Word(word='明日', meaning='tommorow', reading='あした'))
    create_word(db, Word(word='朝', meaning='morning', reading='あさ'))
    create_word(db, Word(word='土曜日', meaning='saturday', reading='どようび'))
    create_word(db, Word(word='日曜日', meaning='sunday', reading='にちようび'))
    create_word(db, Word(word='いつ', meaning='when', reading=''))
    create_word(db, Word(word='行く', meaning='to go', reading='いく'))
    create_word(db, Word(word='帰る', meaning='to return', reading='かえる'))
    create_word(db, Word(word='聞く', meaning='to listen, to ask', reading='きく'))
    create_word(db, Word(word='飲む', meaning='to drink', reading='のむ'))
    create_word(db, Word(word='話す', meaning='to speak', reading='はなす'))
    create_word(db, Word(word='読む', meaning='to read', reading='よむ'))
    create_word(db, Word(word='起きる', meaning='to get up', reading='おきる'))
    create_word(db, Word(word='食べる', meaning='to eat', reading='たべる'))
    create_word(db, Word(word='寝る', meaning='to sleep', reading='ねる'))
    create_word(db, Word(word='見る', meaning='to see', reading='みる'))
    create_word(db, Word(word='来る', meaning='to come', reading='くる'))
    create_word(db, Word(word='する', meaning='to do, to make', reading=''))
    create_word(db, Word(word='勉強する', meaning='to study', reading='べんきょうする'))
    create_word(db, Word(word='良い', meaning='good', reading='いい'))
    create_word(db, Word(word='早い', meaning='early', reading='はやい'))
    create_word(db, Word(word='大抵', meaning='usually, generally', reading='たいてい'))
    create_word(db, Word(word='ちょうっと', meaning='a little', reading=''))
    create_word(db, Word(word='時々', meaning='sometimes', reading='ときどき'))
    create_word(db, Word(word='よく', meaning='often', reading=''))
    create_word(db, Word(word='せんこう', meaning='major', reading=''))
    create_word(db, Word(word='はたち', meaning='20 years old', reading=''))
    create_word(db, Word(word='いっさい', meaning='1 years old', reading=''))
    create_word(db, Word(word='はっさい', meaning='8 years old', reading=''))
    create_word(db, Word(word='じゅっさい', meaning='10 years old', reading=''))
    create_word(db, Word(word='たかい', meaning='expensive', reading=''))
    create_word(db, Word(word='まずい', meaning='unapetable', reading=''))
    create_word(db, Word(word='遅い', meaning='slow, late', reading='おそい'))
    create_word(db, Word(word='狭い', meaning='narrow, restricted', reading='せまい'))
    create_word(db, Word(word='広い', meaning='wide', reading='ひろい'))
    create_word(db, Word(word='明るい', meaning='bright, cheerful', reading='あかるい'))
    create_word(db, Word(word='暗い', meaning='dark', reading='くらい'))
    create_word(db, Word(word='新しい', meaning='new', reading='あたらしい'))
    create_word(db, Word(word='古い', meaning='old (thing)', reading='ふるい'))
    create_word(db, Word(word='小さい', meaning='small', reading='ちいさい'))
    create_word(db, Word(word='大きい', meaning='big, large', reading='おおきい'))
    create_word(db, Word(word='テレビ', meaning='tv', reading=''))
    create_word(db, Word(word='テーブル', meaning='table', reading=''))
    create_word(db, Word(word='ベッド', meaning='bed', reading=''))
    create_word(db, Word(word='エアコン', meaning='AC', reading=''))
    create_word(db, Word(word='椅子', meaning='chair', reading='いす'))
    create_word(db, Word(word='ソファ', meaning='sofa', reading=''))
    create_word(db, Word(word='今晩', meaning='tonight, this evening', reading='こんばん'))
    create_word(db, Word(word='週末', meaning='weekend', reading='しゅうまつ'))
    create_word(db, Word(word='でも', meaning='but', reading=''))
    create_word(db, Word(word='部屋', meaning='room', reading='へや'))
    create_word(db, Word(word='じ', meaning='...hour', reading=''))
    create_word(db, Word(word='全然', meaning='not at all', reading='ぜんぜん'))
    create_word(db, Word(word='ごろ', meaning='...at about', reading=''))
    create_word(db, Word(word='いいえすれ', meaning='thats fine', reading=''))
    create_word(db, Word(word='ゲーム', meaning='game', reading=''))
    create_word(db, Word(word='買い物', meaning='shopping', reading='かいもの'))
    create_word(db, Word(word='クラス', meaning='class', reading=''))
    create_word(db, Word(word='アルバイト', meaning='part-time job', reading=''))
    create_word(db, Word(word='猫', meaning='cat', reading='ねこ'))
    create_word(db, Word(word='人', meaning='person', reading='ひと'))
    create_word(db, Word(word='子供', meaning='child', reading='こども'))
    create_word(db, Word(word='あなた', meaning='you', reading=''))
    create_word(db, Word(word='机', meaning='desk', reading='つくえ'))
    create_word(db, Word(word='写真', meaning='picture', reading='しゃしん'))
    create_word(db, Word(word='花', meaning='flower', reading='はな'))
    create_word(db, Word(word='ラポート', meaning='raport papers', reading=''))
    create_word(db, Word(word='ご飯', meaning='rice', reading='ごはん'))
    create_word(db, Word(word='お寺', meaning='temple', reading='おてら'))
    create_word(db, Word(word='公園', meaning='park', reading='こうえん'))
    create_word(db, Word(word='スーパーマーケット', meaning='supermarket', reading=''))
    create_word(db, Word(word='バス停', meaning='bus stop', reading='ばすてい'))
    create_word(db, Word(word='病院', meaning='hospital', reading='びょういん'))
    create_word(db, Word(word='ホテル', meaning='hotel', reading=''))
    create_word(db, Word(word='本屋', meaning='bookstore', reading='ほんや'))
    create_word(db, Word(word='町', meaning='town', reading='まち'))
    create_word(db, Word(word='レストラン', meaning='restaurant', reading=''))
    create_word(db, Word(word='昨日', meaning='yesterday', reading='きのう'))
    create_word(db, Word(word='時間', meaning='hours', reading='じかん'))
    create_word(db, Word(word='先週', meaning='last week', reading='せんしゅう'))
    create_word(db, Word(word='月曜日', meaning='monday', reading='げつようび'))
    create_word(db, Word(word='火曜日', meaning='tuesday', reading='かようび'))
    create_word(db, Word(word='水曜日', meaning='wednesday', reading='すいようび'))
    create_word(db, Word(word='木曜日', meaning='thursday', reading='もくようび'))
    create_word(db, Word(word='金曜日', meaning='friday', reading='きんようび'))
    create_word(db, Word(word='合う', meaning='to meet (personに)', reading='あう'))
    create_word(db, Word(word='ある', meaning='there is, (placeに thingが) -u', reading=''))
    create_word(db, Word(word='買う', meaning='to buy', reading='かう'))
    create_word(db, Word(word='書く', meaning='to write (personに thingが)', reading='かく'))
    create_word(db, Word(word='撮る', meaning='to take, (a picture) -u verb', reading='とる'))
    create_word(db, Word(word='持つ', meaning='to wait', reading='もつ'))
    create_word(db, Word(word='いる', meaning='is in, stays at (placeに personが)', reading=''))
    create_word(db, Word(word='ぐらい', meaning='about', reading=''))
    create_word(db, Word(word='ごめんなさい', meaning='im sorry', reading=''))
    create_word(db, Word(word='それから', meaning='and then', reading=''))
    create_word(db, Word(word='だから', meaning='so, therefore', reading=''))
    create_word(db, Word(word='たくさん', meaning='many', reading=''))
    create_word(db, Word(word='どうして', meaning='why', reading=''))
    create_word(db, Word(word='一人で', meaning='alone', reading='ひとりで'))
    create_word(db, Word(word='右', meaning='right', reading='みぎ'))
    create_word(db, Word(word='左', meaning='left', reading='ひだり'))
    create_word(db, Word(word='前', meaning='front, before', reading='まえ'))
    create_word(db, Word(word='後ろ', meaning='back, behind', reading='うしろ'))
    create_word(db, Word(word='中', meaning='inside', reading='なか'))
    create_word(db, Word(word='上', meaning='up, above, on', reading='うえ'))
    create_word(db, Word(word='下', meaning='under, below', reading='した'))
    create_word(db, Word(word='近く', meaning='near', reading='ちかく'))
    create_word(db, Word(word='隣', meaning='next to', reading='となり'))
    create_word(db, Word(word='間', meaning='between (XはAとBの)', reading='ないだ'))
    create_word(db, Word(word='しちじ', meaning='7:00', reading=''))
    create_word(db, Word(word='来', meaning='next (week; month; year)', reading='らい'))
    create_word(db, Word(word='今年', meaning='this year', reading='ことし'))
    create_word(db, Word(word='にじゅうよっか', meaning='24th day', reading=''))
    create_word(db, Word(word='じゅうよっか', meaning='14th day', reading=''))
    create_word(db, Word(word='休み', meaning='holiday, day off', reading='やすみ'))
    create_word(db, Word(word='旅行', meaning='travel', reading='りょこう'))
    create_word(db, Word(word='海', meaning='sea, ocean', reading='うみ'))
    create_word(db, Word(word='サーフィン', meaning='surfing', reading=''))
    create_word(db, Word(word='お土産', meaning='suvenir', reading='おみやげ'))
    create_word(db, Word(word='天気', meaning='weather', reading='てんき'))
    create_word(db, Word(word='宿題', meaning='homework', reading='しゅくだい'))
    create_word(db, Word(word='テスト', meaning='test', reading=''))
    create_word(db, Word(word='誕生日', meaning='birthday', reading='たんじょうび'))
    create_word(db, Word(word='僕', meaning='i (man)', reading='ぼく'))
    create_word(db, Word(word='寒い', meaning='cold (weather)', reading='さむい'))
    create_word(db, Word(word='忙しい', meaning='buisy', reading='いそがしい'))
    create_word(db, Word(word='面白い', meaning='interesting, funny', reading='おもしろい'))
    create_word(db, Word(word='つまらない', meaning='boring', reading=''))
    create_word(db, Word(word='易しい', meaning='easy, simple', reading='やさしい'))
    create_word(db, Word(word='難しい', meaning='difficult', reading='むずかしい'))
    create_word(db, Word(word='かっこいい', meaning='good-looking', reading=''))
    create_word(db, Word(word='怖い', meaning='scary', reading='こわい'))
    create_word(db, Word(word='楽しい', meaning='fun', reading='たのしい'))
    create_word(db, Word(word='安い', meaning='cheap, inexpensive', reading='やすい'))
    create_word(db, Word(word='泳ぐ', meaning='to swim', reading='およぐ'))
    create_word(db, Word(word='乗る', meaning='to ride, to board (~に -u verb)', reading='のる'))
    create_word(db, Word(word='やる', meaning='to do (physical action ~を -u verb)', reading=''))
    create_word(db, Word(word='出かける', meaning='to go out, to leave', reading='でかける'))
    create_word(db, Word(word='一緒に', meaning='together', reading='いっしょに'))
    create_word(db, Word(word='すごく', meaning='extremely', reading=''))
    create_word(db, Word(word='大丈夫', meaning='dont worry, its okay', reading='だいじょうぶ'))
    create_word(db, Word(word='とても', meaning='very', reading=''))
    create_word(db, Word(word='どんな', meaning='what kind of...', reading=''))
    create_word(db, Word(word='枚', meaning='flat object counter', reading='まい'))
    create_word(db, Word(word='好きな', meaning='fond of, to like (~が)', reading='すきな'))
    create_word(db, Word(word='嫌いな', meaning='disgusted with, to dislike (~が)', reading='きらいな'))
    create_word(db, Word(word='大好きな', meaning='very fond of, to love (~が)', reading='だいすきな'))
    create_word(db, Word(word='大嫌いな', meaning='to hate (~が)', reading='だいきらいな'))
    create_word(db, Word(word='きれいな', meaning='beautifull, clean', reading=''))
    create_word(db, Word(word='元気な', meaning='healthy, energetic', reading='げんきな'))
    create_word(db, Word(word='静かな', meaning='quiet', reading='しずかな'))
    create_word(db, Word(word='にぎやかな', meaning='lively', reading=''))
    create_word(db, Word(word='暇な', meaning='not busy, free (time)', reading='ひまな'))
    create_word(db, Word(word='暑い', meaning='hot (weather)', reading='あつい'))
    create_word(db, Word(word='熱い', meaning='hot (thing)', reading='あつい'))
    create_word(db, Word(word='ちょっと', meaning='a moment, a little, easily', reading=''))
    create_word(db, Word(word='箱', meaning='box', reading='はこ'))
    create_word(db, Word(word='棚', meaning='shelf', reading='たな'))
    create_word(db, Word(word='カップ', meaning='cup', reading=''))
    create_word(db, Word(word='台所', meaning='kitchen', reading='だいどころ'))
    create_word(db, Word(word='風呂', meaning='bath', reading='ふろ'))
    create_word(db, Word(word='玄関', meaning='entrance, doorway', reading='げんかん'))
    create_word(db, Word(word='庭', meaning='garden', reading='にわ'))
    create_word(db, Word(word='仕事', meaning='work', reading='しごと'))
    create_word(db, Word(word='昼', meaning='daytime', reading='ひる'))
    create_word(db, Word(word='夜', meaning='night', reading='よる'))
    create_word(db, Word(word='漢字', meaning='kanji', reading='かんじ'))
    create_word(db, Word(word='教科書', meaning='textbook', reading='きょうかしょ'))
    create_word(db, Word(word='ページ', meaning='page', reading=''))
    create_word(db, Word(word='次', meaning='next', reading='つぎ'))
    create_word(db, Word(word='荷物', meaning='baggage, package', reading='にもつ'))
    create_word(db, Word(word='パソコン', meaning='personal computer', reading=''))
    create_word(db, Word(word='シャワー', meaning='shower', reading=''))
    create_word(db, Word(word='電気', meaning='electricity, light', reading='でんき'))
    create_word(db, Word(word='窓', meaning='window', reading='まど'))
    create_word(db, Word(word='電車', meaning='train', reading='でんしゃ'))
    create_word(db, Word(word='国', meaning='country', reading='くに'))
    create_word(db, Word(word='今週', meaning='this week', reading='こんしゅう'))
    create_word(db, Word(word='来週', meaning='next week', reading='らいしゅう'))
    create_word(db, Word(word='来年', meaning='next year', reading='らいねん'))
    create_word(db, Word(word='大変な', meaning='tough (situation)', reading='たいへんな'))
    create_word(db, Word(word='遊ぶ', meaning='to play', reading='あそぶ'))
    create_word(db, Word(word='急ぐ', meaning='to hurry', reading='いそぐ'))
    create_word(db, Word(word='返す', meaning='to return, to repay (a thing personに thingを)', reading='かえす'))
    create_word(db, Word(word='消す', meaning='to erase (~を), to turn off', reading='けす'))
    create_word(db, Word(word='死ぬ', meaning='to die', reading='しぬ'))
    create_word(db, Word(word='座る', meaning='to sit down (-u verb seatに)', reading='すわる'))
    create_word(db, Word(word='立つ', meaning='to stand up', reading='たつ'))
    create_word(db, Word(word='たばこを吸う', meaning='to smoke', reading='たばこをすう'))
    create_word(db, Word(word='使う', meaning='to use (~を)', reading='つかう'))
    create_word(db, Word(word='手伝う', meaning='to help (person/task を)', reading='てつだう'))
    create_word(db, Word(word='入る', meaning='to enter (-u verb ~に) ', reading='はいる'))
    create_word(db, Word(word='休む', meaning='to be absent (from ~を), to rest', reading='やすむ'))
    create_word(db, Word(word='開ける', meaning='to open (something ~を)', reading='あける'))
    create_word(db, Word(word='閉める', meaning='to close (something ~を)', reading='しめる'))
    create_word(db, Word(word='教える', meaning='to teach, to instruct (personに thingを)', reading='おしえる'))
    create_word(db, Word(word='忘れる', meaning='to forget, to leave behind (~を)', reading='わすれる'))
    create_word(db, Word(word='降りる', meaning='to get off, to land (~を)', reading='おりる'))
    create_word(db, Word(word='借りる', meaning='to borrow (personに thingを)', reading='かりる'))
    create_word(db, Word(word='浴びる', meaning='to take a shower', reading='あびる'))
    create_word(db, Word(word='つける', meaning='to turn on (~を)', reading=''))
    create_word(db, Word(word='電話する', meaning='to call (~に)', reading='でんわする'))
    create_word(db, Word(word='連れて来る', meaning='to bring (a person ~を)', reading='つれてくる'))
    create_word(db, Word(word='持って来る', meaning='to bring (a thing ~を)', reading='もってくる'))
    create_word(db, Word(word='後で', meaning='later on', reading='あとで'))
    create_word(db, Word(word='すぐ', meaning='right away', reading=''))
    create_word(db, Word(word='ゆっくり', meaning='slowly', reading=''))
    create_word(db, Word(word='結構です', meaning='that would be fine, that wouldnt be necessary', reading='けっこうです'))
    create_word(db, Word(word='本当にですか', meaning='really?', reading='ほんとうですか'))
